version: "3"
services:
  frontend:
    image: ghcr.io/int371-13-49-129/int371:dev
    container_name: frontend
    networks:
       allnetwork:
          ipv4_address: 172.20.0.2
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
