version: "3"
services:
  frontend:
    container_name: frontend
    image: ghcr.io/int371-13-49-129/int371front:dev
    networks:
       allnetwork:
          ipv4_address: 172.20.0.2
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
